### ISSUE TITLE
29 - Research data aggregation using Amplify

### ISSUE THREAD

**Issue by jlaksana** [hack4impact-calpoly/wilshire-hope-chest#29]
As an administrator, I want to see relevant data about different metrics in a timeframe.

We still do not know exactly what kind of aggregate data the nonprofit wants but we can still prepare for it. Research our options for how to write a query to get aggregate data. For example, we could get the total number of donated items per category or the total value per category. When closing this, include in the options you found, some pros and cons of each, and the resources you used. You could also provide your recommendation of which option to go with.

- [ ] Research all ways to query/get/store aggregate data with Amplify
- [ ] Write a report of your findings

**Additional context**
You can view our data definitions in Amplify Studio under the Data tab.

*See comment on more requirements*

**Comment by jlaksana** [comment]
After reviewing the requirements with the non-profit, they would like a report of the total donated value between two dates. We can do this but keep exploring how to get the total value per category as well.

**Comment by SilverXer0** [comment]
Got it, will do research on both

**Comment by SilverXer0** [comment]
https://docs.google.com/document/d/1xpt3dpF-Jj962CMriCN-68lAECkTdKRTR7FQKv0M36E/edit?usp=sharing
